import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import AppProvider from "@/components/AppContext";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className} suppressHydrationWarning={true}>
        <AppProvider>
          <Header />
          <main className="max-w-4xl mx-auto p-4">
            {children}
            <Toaster />
          </main>
          <footer className="border-t p-8 text-center text-gray-500 mt-16">
            &copy; 2024 All rights reserved
          </footer>
        </AppProvider>
      </body>
    </html>
  );
}
